---
title: "R vs SAS Satterthwaite Degrees of Freedom Method"
execute:
  eval: false
---

# R vs SAS Satterthwaite Degrees of Freedom Method

## Introduction of data and notation

The dataset is supposed to mimic a stage 3 clinical trial on Alzheimer's disease, with 6 observations per patient each taken during visits at 0, 6, 12, 18, 24 and 36 months. The measurement taken during each visit is the result from an ADAS-Cog (Alzheimer's Disease Assessment Scale - Cognitive Section) test, which is a scale ranging from 0 to 85 testing the memory and mental capabilities of the patient. Half of the patients are in an active treatment group ($act$) while the rest are in a placebo treatment group ($pbo$). The data is simulated from a normal distribution with a given mean vector and variance-covariance matrix. The code used to generate the dataset is seen below:

```{r}
simulate_trial <- function(n_arm = 500, # Number of patients per group
                           M = c(0, 6, 12, 18, 24, 36), # Months in which an observation is to be taken
                           drop_out = 0, # Drop out factor
                           mean_pbo, # Mean values for visits in the placebo group
                           mean_act, # Mean values for visits in the active group
                           cov_sqrt) { #Cholesky Decomposition of Variance-Covariance matrix
  
  # Simulate data
  m <- length(M) # Number of measurements per patient
  y_pbo <- cov_sqrt %*% matrix(rnorm(m * n_arm), nrow = m) + mean_pbo # Create the measurements for the placebo group
  y_act <- cov_sqrt %*% matrix(rnorm(m * n_arm), nrow = m) + mean_act # Create the measurements for the active group
  
  # Create dataset
  dat <- data.frame(id = rep(1:(2 * n_arm), each = m), # Patient IDs
                    visit = factor(rep(1:m, 2 * n_arm)), # Visits
                    M = rep(M, n_arm), # Months since baseline
                    y = c(as.numeric(y_pbo), as.numeric(y_act)), # Outcome measure
                    trt = factor(rep(c('pbo', 'act'), each = n_arm * m)), # Treatment arm
                    act = rep(c(0, 1), each = n_arm * m)) # Dummy treatment arm
  
  dat$mod_trt <- dat$trt
  dat$mod_trt[dat$M == 0] <- 'pbo' # Cast 
  dat$act <- as.numeric(dat$trt == 'act')
  dat$act_vis <- with(dat, interaction(mod_trt, M))
  
  # Implement per-visit drop out
  for (v in M) {
    ids <- unique(subset(dat, M >= v)$id) # Find number of patients left in study
    # Sample 
    id_rm <- sample(ids, 
                    size = floor(length(ids) * drop_out)) # Sample drop_out percentage of patients still in the study
    dat <- subset(dat, !(M >= v & (id %in% id_rm))) # Remove sampled patients from study
  }
  
  return(dat) 
}

```

## Basic Model, Estimates, and Hypothesis Test of Contrast

## Same as above, but now with tau\^2 = 80 and sigma\^2 = 0.001

## Unstructured Variance-Covariance Matrix for Data Simulation

## Model with Random Slope and Estimates

## Degrees of Freedom Plot and Differences between the Two Procedures
